import { ipcMain, BrowserWindow } from 'electron'
import { readFile, writeFile } from 'fs/promises'
import { join } from 'path'

export type TexCompiler = 'pdflatex' | 'xelatex' | 'lualatex' | 'platex' | 'uplatex'
export type TexLiveVersion = '2018' | '2019' | '2020' | '2021' | '2022' | '2023' | '2024' | '2025'

export interface LatexmkSettings {
  compiler: TexCompiler
  mainFile: string
  texLiveVersion: TexLiveVersion
}

const LATEXMKRC_FILE = '.latexmkrc'

// Map compiler to latexmk $pdf_mode
function getPdfMode(compiler: TexCompiler): number {
  switch (compiler) {
    case 'pdflatex':
      return 1
    case 'lualatex':
      return 4
    case 'xelatex':
      return 5
    case 'platex':
    case 'uplatex':
      return 3 // dvipdf mode
    default:
      return 1
  }
}

// Get compiler command with options
function getCompilerCommand(compiler: TexCompiler): string {
  const commonOpts = '-interaction=nonstopmode -file-line-error -synctex=1'
  switch (compiler) {
    case 'pdflatex':
      return `pdflatex ${commonOpts} %O %S`
    case 'xelatex':
      return `xelatex ${commonOpts} %O %S`
    case 'lualatex':
      return `lualatex ${commonOpts} %O %S`
    case 'platex':
      return `platex ${commonOpts} %O %S`
    case 'uplatex':
      return `uplatex ${commonOpts} %O %S`
    default:
      return `pdflatex ${commonOpts} %O %S`
  }
}

// Generate .latexmkrc content from settings
export function generateLatexmkrc(settings: LatexmkSettings): string {
  const pdfMode = getPdfMode(settings.compiler)
  const compilerCmd = getCompilerCommand(settings.compiler)
  const mainFileBase = settings.mainFile.replace(/\.tex$/, '')

  let content = `# Generated by Paper Writer - Do not edit manually unless you know what you're doing
# Settings can be changed via Paper Writer UI or by editing this file directly

# PDF generation mode
$pdf_mode = ${pdfMode};

`

  // Add compiler command based on type
  if (settings.compiler === 'pdflatex') {
    content += `# pdfLaTeX compiler
$pdflatex = '${compilerCmd}';
`
  } else if (settings.compiler === 'xelatex') {
    content += `# XeLaTeX compiler
$xelatex = '${compilerCmd}';
`
  } else if (settings.compiler === 'lualatex') {
    content += `# LuaLaTeX compiler
$lualatex = '${compilerCmd}';
`
  } else if (settings.compiler === 'platex' || settings.compiler === 'uplatex') {
    content += `# Japanese LaTeX compiler
$latex = '${compilerCmd}';
$dvipdf = 'dvipdfmx %O -o %D %S';
`
  }

  content += `
# Main document
@default_files = ('${settings.mainFile}');

# TeX Live version path (uncomment and adjust if needed)
# $ENV{'PATH'} = '/usr/local/texlive/${settings.texLiveVersion}/bin/x86_64-darwin:' . $ENV{'PATH'};

# Clean up auxiliary files
$clean_ext = 'synctex.gz synctex.gz(busy) run.xml tex.bak bbl bcf fdb_latexmk run tdo %R-blx.aux %R-blx.bib';

# Output directory (same as source)
$out_dir = '.';

# Biber/BibTeX
$bibtex_use = 2;
$biber = 'biber %O %S';
`

  return content
}

// Parse .latexmkrc to extract settings
export function parseLatexmkrc(content: string): Partial<LatexmkSettings> {
  const settings: Partial<LatexmkSettings> = {}

  // Parse $pdf_mode
  const pdfModeMatch = content.match(/\$pdf_mode\s*=\s*(\d+)/)
  if (pdfModeMatch) {
    const mode = parseInt(pdfModeMatch[1], 10)
    switch (mode) {
      case 1:
        settings.compiler = 'pdflatex'
        break
      case 4:
        settings.compiler = 'lualatex'
        break
      case 5:
        settings.compiler = 'xelatex'
        break
      case 3:
        // Could be platex or uplatex, check $latex
        if (content.includes('uplatex')) {
          settings.compiler = 'uplatex'
        } else {
          settings.compiler = 'platex'
        }
        break
    }
  }

  // Parse @default_files
  const defaultFilesMatch = content.match(/@default_files\s*=\s*\(\s*['"]([^'"]+)['"]/)
  if (defaultFilesMatch) {
    settings.mainFile = defaultFilesMatch[1]
  }

  // Parse TeX Live version from PATH
  const texliveMatch = content.match(/texlive\/(\d{4})\/bin/)
  if (texliveMatch) {
    settings.texLiveVersion = texliveMatch[1] as TexLiveVersion
  }

  return settings
}

// Read .latexmkrc from project
export async function readLatexmkrc(projectPath: string): Promise<Partial<LatexmkSettings> | null> {
  const rcPath = join(projectPath, LATEXMKRC_FILE)
  try {
    const content = await readFile(rcPath, 'utf-8')
    return parseLatexmkrc(content)
  } catch {
    return null
  }
}

// Write .latexmkrc to project
export async function writeLatexmkrc(projectPath: string, settings: LatexmkSettings): Promise<void> {
  const rcPath = join(projectPath, LATEXMKRC_FILE)
  const content = generateLatexmkrc(settings)
  await writeFile(rcPath, content, 'utf-8')
}

// Get default settings
export function getDefaultLatexmkSettings(): LatexmkSettings {
  return {
    compiler: 'pdflatex',
    mainFile: 'main.tex',
    texLiveVersion: '2025'
  }
}

// Notify renderer about latexmkrc changes
export function notifyLatexmkrcChange(settings: Partial<LatexmkSettings>): void {
  const windows = BrowserWindow.getAllWindows()
  for (const win of windows) {
    win.webContents.send('latexmkrc:changed', settings)
  }
}

// Register IPC handlers for latexmkrc
export function registerLatexmkConfigHandlers(): void {
  // Read latexmkrc settings
  ipcMain.handle('latexmkrc:read', async (_, projectPath: string): Promise<LatexmkSettings> => {
    const settings = await readLatexmkrc(projectPath)
    if (settings) {
      return {
        ...getDefaultLatexmkSettings(),
        ...settings
      }
    }
    return getDefaultLatexmkSettings()
  })

  // Write latexmkrc settings
  ipcMain.handle('latexmkrc:write', async (_, projectPath: string, settings: LatexmkSettings): Promise<void> => {
    await writeLatexmkrc(projectPath, settings)
  })

  // Get available .tex files for main document selection
  ipcMain.handle('latexmkrc:getTexFiles', async (_, projectPath: string): Promise<string[]> => {
    const { readdir } = await import('fs/promises')
    const { join } = await import('path')

    const files: string[] = []

    async function scanDir(dir: string, prefix: string = ''): Promise<void> {
      try {
        const entries = await readdir(dir, { withFileTypes: true })
        for (const entry of entries) {
          if (entry.isDirectory() && !entry.name.startsWith('.')) {
            await scanDir(join(dir, entry.name), prefix ? `${prefix}/${entry.name}` : entry.name)
          } else if (entry.isFile() && entry.name.endsWith('.tex')) {
            files.push(prefix ? `${prefix}/${entry.name}` : entry.name)
          }
        }
      } catch {
        // Ignore errors
      }
    }

    await scanDir(projectPath)
    return files.sort()
  })
}
