# Generated by Paper Writer - Do not edit manually unless you know what you're doing
# Settings can be changed via Paper Writer UI or by editing this file directly

# PDF generation mode
$pdf_mode = 1;

# pdfLaTeX compiler
$pdflatex = 'pdflatex -interaction=nonstopmode -file-line-error -synctex=1 %O %S';

# Main document
@default_files = ('main.tex');

# TeX Live version path (uncomment and adjust if needed)
# $ENV{'PATH'} = '/usr/local/texlive/2025/bin/x86_64-darwin:' . $ENV{'PATH'};

# Clean up auxiliary files
$clean_ext = 'synctex.gz synctex.gz(busy) run.xml tex.bak bbl bcf fdb_latexmk run tdo %R-blx.aux %R-blx.bib';

# Output directory (same as source)
$out_dir = '.';

# Biber/BibTeX
$bibtex_use = 2;
$biber = 'biber %O %S';
